items:
  urgent:
  - '技巧概要·卷1'
  - '技巧概要·卷2'
  normal:
  - '初级作战记录'
  - '固源岩'
  - '源岩'
  - '装置'
  - '破损装置'
  - '聚酸酯'
  - '酯原料'
  - '糖组'
  - '糖'
  - '代糖'
  - '异铁'
  - '异铁碎片'
  - '酮凝集'
  - '双酮'
  - '赤金'
  - '龙门币'
  - '招聘许可'
  excluded:
  - '碳素'
  - '碳'
  - '加急许可'
  - '家具零件'