drone_mode: auto # auto, manual
drone_auto_gold_threshold: 20
drone_auto_operation_when_few_gold: produce_exp
drone_auto_operation_when_much_gold: trade_gold
drone_manual_operation: produce_exp # trade_gold, produce_exp