refill_with_item: false
plan:
- stages:
  - DV-6: 25
    //: ' '
    sanity: 21
    remain: 3
- stages:
  - DV-6: 100
    //: ' '
    sanity: 21
    remain: 100
  - DV-7: 100
    //: ' '
    sanity: 21
    remain: 100
  - DV-8: 100
    //: ' '
    sanity: 21
    remain: 100
- planner:  # 泥岩2技能专三
  - 技能书3合成: 35
  - 晶体电路: 4
  - 凝胶: 3
  - 聚合凝胶: 4
  - 提纯源岩: 10
  - 聚合剂: 6
  - 炽合金块: 6
- planner:  # 每日轮换材料储备
  - 净龙门币: 210000
  - 采购凭证: 360
  - 医疗芯片: 5
  - 重装芯片: 5
  - 狙击芯片: 5
  - 术师芯片: 5
  - 先锋芯片: 5
  - 辅助芯片: 5
  - 近卫芯片: 5
  - 特种芯片: 5
  - 医疗芯片组: 8
  - 重装芯片组: 8
  - 狙击芯片组: 8
  - 术师芯片组: 8
  - 先锋芯片组: 8
  - 辅助芯片组: 8
  - 近卫芯片组: 8
  - 特种芯片组: 8
  - 技能书3合成: 40
  - 技能书2: 30
  - 技能书1: 30
- blue_item:
# TODO:
# - 泥岩 2专三
# - 风笛 3专三
# - 凯尔希 2专三
# - 铃兰 3专三
# - 风笛 2专三
