refill_with_item: false
plan:
- blue_item: 10
- planner:  # 每日轮换材料储备 (10人份)
  - 净龙门币: 2000000
  - 医疗芯片: 25
  - 重装芯片: 25
  - 狙击芯片: 25
  - 术师芯片: 25
  - 先锋芯片: 25
  - 辅助芯片: 25
  - 近卫芯片: 25
  - 特种芯片: 25
  - 医疗双芯片: 20
  - 重装双芯片: 20
  - 狙击双芯片: 20
  - 术师双芯片: 20
  - 先锋双芯片: 20
  - 辅助双芯片: 20
  - 近卫双芯片: 20
  - 特种双芯片: 20
  - 技能书3合成: 200
  - 采购凭证: 3000
- blue_item: 100
- blue_item:
- eval:
  - 1-7: 1
- eval:
  - BI-6: 1
- eval:
  - BI-6: max(owned['炽合金'], owned['聚酸酯组'], owned['研磨石']) - owned['炽合金'] + 1
  - BI-7: max(owned['炽合金'], owned['聚酸酯组'], owned['研磨石']) - owned['聚酸酯组'] + 1
  - BI-8: max(owned['炽合金'], owned['聚酸酯组'], owned['研磨石']) - owned['研磨石'] + 1
- stages:
  - NL-2: 1
    //: ' '
    sanity: 9
    remain: 0
  - NL-8: 1
    //: ' '
    sanity: 18
    remain: 0
- eval:
  - NL-8: max(owned['糖组'], owned['晶体元件'], owned['扭转醇']) - owned['糖组'] + 1
  - NL-9: max(owned['糖组'], owned['晶体元件'], owned['扭转醇']) - owned['晶体元件'] + 1
  - NL-10: max(owned['糖组'], owned['晶体元件'], owned['扭转醇']) - owned['扭转醇'] + 1
- eval:
  - 1-7: 7*20 - owned['提纯源岩']*20 - owned['固源岩组']*5 - owned['固源岩']