refill_with_item: false
plan:
- blue_item: 100
- planner:  # 每日轮换材料储备
  - 净龙门币: 420000
  - 医疗芯片: 10
  - 重装芯片: 10
  - 狙击芯片: 10
  - 术师芯片: 10
  - 先锋芯片: 10
  - 辅助芯片: 10
  - 近卫芯片: 10
  - 特种芯片: 10
  - 医疗芯片组: 16
  - 重装芯片组: 16
  - 狙击芯片组: 16
  - 术师芯片组: 16
  - 先锋芯片组: 16
  - 辅助芯片组: 16
  - 近卫芯片组: 16
  - 特种芯片组: 16
  - 技能书3合成: 40
  - 技能书2: 30
  - 技能书1: 30
  - 采购凭证: 720
- blue_item:
- stages:
  - NL-2: 1
    //: ' '
    sanity: 9
    remain: 0
  - NL-8: 1
    //: ' '
    sanity: 18
    remain: 0
- eval:
  - NL-8: max(owned['糖组'], owned['晶体元件'], owned['扭转醇']) - owned['糖组'] + 1
  - NL-9: max(owned['糖组'], owned['晶体元件'], owned['扭转醇']) - owned['晶体元件'] + 1
  - NL-10: max(owned['糖组'], owned['晶体元件'], owned['扭转醇']) - owned['扭转醇'] + 1
- eval:
  - 1-7: 7*20 - owned['提纯源岩']*20 - owned['固源岩组']*5 - owned['固源岩']
- eval:
  - 1-7: 1