refill_with_item: false
plan:
- stages:
  - NL-8: 9999
    //: ' '
    sanity: 18
    remain: 9921
- planner:  # 每日轮换材料储备
  - 净龙门币: 420000
  - 医疗芯片: 10
  - 重装芯片: 10
  - 狙击芯片: 10
  - 术师芯片: 10
  - 先锋芯片: 10
  - 辅助芯片: 10
  - 近卫芯片: 10
  - 特种芯片: 10
  - 医疗芯片组: 16
  - 重装芯片组: 16
  - 狙击芯片组: 16
  - 术师芯片组: 16
  - 先锋芯片组: 16
  - 辅助芯片组: 16
  - 近卫芯片组: 16
  - 特种芯片组: 16
  - 技能书3合成: 40
  - 技能书2: 30
  - 技能书1: 30
  - 采购凭证: 720
- eval:
  - 1-7: 1
- blue_item:
