refill_with_item: false
plan:
- stages:
  - AP-5: 9999
    //: 红票
- stages:
  - CE-5: 1000
    //: 来点钱钱
- planner:
  - 双极纳米片: 5
  - 龙门币: 1000000
- blue_item:  # 刷最少的蓝材料




refill_with_item: false
plan:
- stages:
  - SK-5: 9999
    //: 碳
    sanity: 30
    remain: 9999
- planner:
  - 龙门币: 180000
- planner:
  - 双极纳米片: 5
- blue_item:




# Planner支持的特殊字段：
# 龙门币，经验，