# 公开招募券消耗策略
strategy: fast
# fast: 在没有刷新机会的情况下继续三星标签组合（默认），有四星保底时要四星，五星六星不招募（通知）
# slow: 以办公室刷新为优先，不接受三星组合，仅当出现四星保底组合时才招募，五星六星不招募（通知）


# 当一星小车与四星保底标签同时出现时优先选择哪种
1or4: 4


pool:
- '风笛'
- '推进之王'
- '陈'
- '赫拉格'
- '煌'
- '斯卡蒂'
- '银灰'
- '黑'
- '能天使'
- '塞雷娅'
- '星熊'
- '闪灵'
- '夜莺'
- '麦哲伦'
- '刻俄柏'
- '莫斯提马'
- '伊芙利特'
- '阿'
- 'Castle-3'
- 'THRM-EX'
- '夜刀'
- '黑角'
- '芬'
- '翎羽'
- '香草'
- '玫兰莎'
- '泡普卡'
- '月见夜'
- '斑点'
- '米格鲁'
- '红豆'
- '清道夫'
- '桃金娘'
- '艾丝黛尔'
- '缠丸'
- '杜宾'
- '猎蜂'
- '慕斯'
- '霜叶'
- '宴'
- '古米'
- '角峰'
- '蛇屠箱'
- '阿消'
- '暗索'
- '砾'
- '德克萨斯'
- '凛冬'
- '苇草'
- '布洛卡'
- '诗怀雅'
- '星极'
- '因陀罗'
- '幽灵鲨'
- '吽'
- '火神'
- '可颂'
- '雷蛇'
- '临光'
- '红'
- '槐琥'
- '狮蝎'
- '食铁兽'
- '崖心'
- '正义骑士号'
- 'Lancet-2'
- '巡林者'
- '12F'
- '杜林'
- '安德切尔'
- '克洛丝'
- '空爆'
- '安赛尔'
- '芙蓉'
- '梓兰'
- '史都华德'
- '炎熔'
- '安比尔'
- '白雪'
- '红云'
- '杰西卡'
- '流星'
- '梅'
- '调香师'
- '末药'
- '清流'
- '苏苏洛'
- '地灵'
- '格雷伊'
- '夜烟'
- '远山'
- '白金'
- '灰喉'
- '蓝毒'
- '普罗旺斯'
- '慑砂'
- '守林人'
- '送葬人'
- '陨星'
- '白面鸮'
- '赫默'
- '华法琳'
- '初雪'
- '格劳克斯'
- '梅尔'
- '真理'
- '惊蛰'
- '夜魔'
- '傀影'
- '巫恋'
- '刻刀'
- '温蒂'
- '极境'
- '石棉'
- '月禾'